apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  selector:
    matchLabels:
      app: database-app
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: database-app
    spec:
      containers:
        - name: database
          image: "postgres:12.1"
          resources:
            requests:
              cpu: 1.2
              memory: 5Gi
            limits:
              cpu: 1.2
              memory: 5Gi
          env:
            # PGDATA should be a subdir of the mount, so there's no lost+found.
            # Make it include version number, so we can pg_upgrade using
            # https://github.com/tianon/docker-postgres-upgrade someday.
            # (Upgrade moves data files instead of copying, if source and
            # destination are on same disk; that's the dream.)
            - name: PGDATA
              value: /var/lib/postgresql/data/12
            # Set user/password/db to cjworkbench. We only ever have one DB,
            # and every user has full access. (TODO implement user control.)
            - name: POSTGRES_USER
              value: cjworkbench
            - name: POSTGRES_PASSWORD
              value: cjworkbench
            - name: POSTGRES_DB
              value: cjworkbench
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-volume
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: dbdata-pvc
