apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: worker-app
  replicas: 2
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
        - name: worker
          image: "gcr.io/cj-workbench/worker:latest"
          resources:
            requests:
              cpu: 1.01 # don't put two workers on a 2-CPU machine
              memory: 5250Mi # basically the max on an n1-standard-2 running fluentd
            limits:
              cpu: 1.9
              memory: 5250Mi
          env:
            - name: CJW_PRODUCTION
              value: 'True'
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: ASGI_THREADS
              value: '5'
            - name: CJW_DB_HOST
              value: database-service
            - name: CJW_DB_PASSWORD
              value: cjworkbench
            - name: CJW_SECRET_KEY
              value: worker-needs-no-secret-key
            - name: CJW_WORKER_N_RENDERERS
              value: "1"
            - name: CJW_WORKER_N_FETCHERS
              value: "3"
            - name: CJW_SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cjw-sendgrid-api-key
                  key: value
            - name: CJW_SENDGRID_INVITATION_ID
              value: b22cb75d-2673-4efe-88d3-22239eaf403c
            - name: CJW_SENDGRID_CONFIRMATION_ID
              value: 86182412-e2bd-4d9f-be7d-a535a9f8e50b
            - name: CJW_SENDGRID_PASSWORD_CHANGE_ID
              value: 049f32e5-06ef-42e5-847d-ca30f52bf816
            - name: CJW_SENDGRID_PASSWORD_RESET_ID
              value: 0946d35d-5763-4a22-b17d-ed9cb42bf096
            - name: CJW_GOOGLE_CLIENT_SECRETS
              value: secrets/google-oauth-secret/google-oauth-secret.json
            - name: CJW_SOCIALACCOUNT_SECRETS
              value: secrets/socialaccount-secrets/socialaccount-secrets.json
            - name: CJW_TWITTER_CLIENT_SECRETS
              value: secrets/twitter-oauth-secret/twitter-oauth-secret.json
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: secret_key
            - name: MINIO_BUCKET_PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MINIO_EXTERNAL_URL
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: external_url
            - name: MINIO_URL
              value: http://minio-service
            - name: MINIO_BUCKET_SUFFIX
              value: '.workbenchdata.com'
            - name: _RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-1-rabbitmq-secret
                  key: rabbitmq-pass
            - name: CJW_RABBITMQ_HOST
              value: "amqp://rabbit:$(_RABBITMQ_PASSWORD)@rabbitmq-1-rabbitmq-svc/"
          volumeMounts:
            - mountPath: /app/secrets/google-oauth-secret
              name: google-oauth-secret
              readOnly: true
            - mountPath: /app/secrets/socialaccount-secrets
              name: socialaccount-secrets
              readOnly: true
            - mountPath: /app/secrets/twitter-oauth-secret
              name: twitter-oauth-secret
              readOnly: true
      volumes:
        - name: google-oauth-secret
          secret:
            secretName: google-oauth-secret
            items:
              - key: json
                path: google-oauth-secret.json
        - name: socialaccount-secrets
          secret:
            secretName: socialaccount-secrets
            items:
              - key: json
                path: socialaccount-secrets.json
        - name: twitter-oauth-secret
          secret:
            secretName: twitter-oauth-secret
            items:
              - key: json
                path: twitter-oauth-secret.json
